### ISSUE TITLE
Remove code chunks

### ISSUE THREAD

**Issue by ratnanil** [SagerRamon/Wild-Boar-Project#3]
As I had written [on moodle](https://moodle.zhaw.ch/mod/forum/discuss.php?d=53346#p86502), you should 

> hide your R Code from your output, since the code makes your report less legible. You can hide the code from your entire document by adding the following code chunk to the top of your document:

````
```{r, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```
````

Can you add this to your document and then re-knit your analysis? Please close this issue after you have done so.

**Comment by SagerRamon** [comment]
I removed the code, however we based the text also on the code... so maybe we have overseen some relicts from that.
